services:
  angular:
    env_file:
      - .env


    build:
      context: ./web
      args:
        - USER_ID=${USER_ID}
        - GROUP_ID=${GROUP_ID}
        - USERNAME=${USERNAME}
    restart: "no"
    ports:
      - 127.0.0.1:4200:4200
    command: ng serve --host 0.0.0.0 --port 4200 --poll=1000
    volumes: 
      - ./web:/usr/src/web


